### ISSUE TITLE
Need to handle special characters that are present in the testcase titles.

### ISSUE THREAD

**Issue by AnurupaIkkurthi** [vidyutron/UnifiedFramework#2]

**Comment by vidyutron** [comment]
Added "UnifiedCleanser" feature, which facilitates easier handling of different cases of Special Characters, for your case the bug was with the "double quotes", so now as part of excel reading logic user is needed to pass extra UnifiedCleanser argument. Please refer the updated ReadMe markup file.

Older code block- 
uCodeExcelRead = component.ExcelReader(filePath, "TestCaseFileName", "SheetName");
Updated Code block-
uCodeExcelRead = component.ExcelReader(filePath, "TestCaseFileName", "SheetName",UnifiedCleanser.QuotesCleanser);

**Comment by vidyutron** [comment]
Please take latest Nuget from UnifiedFramework.Nuget folder of 'mods' branch. File name format--{UnifiedFramework.1.x.x.x.nupkg}
